import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quarta Entrega',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        
        <header className="bg-gray-700 text-white">
            <h1>Produtos</h1>
              <ul>
                <li><Link href="/">Home</Link></li>
                <li><Link href="./produtos/tenis">Tenis</Link></li>
                <li><Link href="./produtos/calca">Calça</Link></li>
                <li><Link href="./produtos/camisa">Camisa</Link></li>
                <li><Link href="./produtos/meia">Meia</Link></li>
              </ul>
        </header>
        
        {children}
      
      </body>
    </html>
  )
}
